fluent-plugins-nursery/winevt_c

ext/winevt/extconf.rb
ext/winevt/winevt_c.h
ext/winevt/winevt_channel.c
ext/winevt/winevt_query.c
ext/winevt/winevt_subscribe.c
ext/winevt/winevt_utils.cpp
test/test_winevt.rb

I've added `-Wall` to `CFLAGS` and suppress compile time warnings found by it.
In addition, remove some unused functions.
Some of such warnings are harmless, but some of them cause actual issues.
Please check patches one by one.

Suppress compile time warnings

---

example/rate_limit.rb
ext/winevt/winevt_c.h
ext/winevt/winevt_subscribe.c
test/test_winevt.rb

I've implemented a naive rate limit feature.
This feature should be disabled by default.

subscribe: Implement API rate limit feature

---

ext/winevt/winevt_c.h
ext/winevt/winevt_query.c
test/test_winevt.rb

Fixes #2 .
The previous implementation does not permit complex seek flag such as:
`EvtSeekRelativeToLast | EvtSeekStrict`
This patch is quite native implementation because the current patch cannot handle why the wrong complex flag values are not accepted.
What should we handle wrong flag circumstances?

query: Handle complex seek flag

---

ext/winevt/winevt_c.h
ext/winevt/winevt_subscribe.c
ext/winevt/winevt_utils.cpp
test/test_winevt.rb

In the previous code GetLastError() may not be called for
EvtSubscribe().
In addition, the error message isn't internationalized since
FormatMessageA() was used. This commit replaces it with
FormatMessageW().
Other error handlings should use FormatMessageW() too, so I'll replace
them later.

Add missing error handlings for rb_winevt_subscribe_subscribe()

---

ext/winevt/winevt_subscribe.c
lib/winevt.rb
lib/winevt/bookmark.rb
lib/winevt/subscribe.rb
test/test_winevt.rb

In the previous implementation, Bookmark instance may be double freed.
In Subscribe class, Bookmark handle should be created from Bookmark XML.
But existing API should not break.

Create Bookmark handle in #subscribe safely

---

.travis.yml

Nowadays, fat gem should be deprecated but td-agent users usually do not
have MSYS2 system in their production/staging environment.
We still need to maintenance fat gem building process.

Build fat gem with rake-compiler-dock

---

ext/winevt/winevt_subscribe.c
test/test_winevt.rb

* Discard previous subscription member handle
* Should close subscribe, bookmark, and signal event handles before raising exception

Plug memory leaks in subscribe#subscribe in mainly error handling cases

---

example/enumerate_channels.rb
ext/winevt/winevt_c.h
ext/winevt/winevt_channel.c
test/test_winevt.rb

This feature is needed for enumerating all subscribable channel.
Based on these lines' idea:
https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs#L627-L633
Debug and Analytical type of channel are not subscribable.
Related to https://github.com/fluent/fluent-plugin-windows-eventlog/issues/47, https://github.com/fluent/fluent-plugin-windows-eventlog/pull/48#discussion_r384901296.

Check subscribable type for channel

---

ext/winevt/winevt_utils.cpp

DWORD is long unsigned int.
So, to convert into Ruby Ruby object, We should use ULONG2NUM here.
Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>
Otherwise, the following qualifiers should cause eventID variable overflow:
```
{:eventlog=>"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-SPP' Guid='{E23B33B0-C8C9-472C-A5F9-F2BDFEA0F156}' EventSourceName='Software Protection Platform Service'/><EventID Qualifiers='49152'>16394</EventID><Version>0</Version><Level>4</Level><Task>0</Task><Opcode>0</Opcode><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime='2020-01-18T05:12:11.443573600Z'/><EventRecordID>152570</EventRecordID><Correlation/><Execution ProcessID='0' …
```

Fix EventID overflow in converting to Ruby object macro

---

ext/winevt/winevt.c
ext/winevt/winevt_bookmark.c
ext/winevt/winevt_c.h
ext/winevt/winevt_channel.c
ext/winevt/winevt_query.c

Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>
`winevt_c` gem also should be fixed like as `certstore_c` gem....

Fix building error with mingw-w64 gcc 10.1

---

ext/winevt/winevt_locale.c
test/test_winevt.rb

For using Fluentd plugin, specifying invalid locale should be notified as exception.
In Fluentd side, invalid configuration should notify as exception.
Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>

Handle invalid locale as ArgmentError exception

---

example/eventlog.rb
example/tailing.rb
ext/winevt/winevt.c
ext/winevt/winevt_c.h
ext/winevt/winevt_query.c
ext/winevt/winevt_session.c
ext/winevt/winevt_subscribe.c
ext/winevt/winevt_utils.cpp
lib/winevt.rb
lib/winevt/session.rb
lib/winevt/subscribe.rb
test/test_winevt.rb

To confirm this, we should prepare Windows Firewall for RPC login and adding EventLog Readers group into accessing account:
https://help.sumologic.com/03Send-Data/Sources/01Sources-for-Installed-Collectors/Remote-Windows-Event-Log-Source/Preconfigure-a-Machine-to-Collect-Remote-Windows-Events

Implement remoting Windows EventLog access

---

ext/winevt/winevt_query.c
ext/winevt/winevt_subscribe.c
test/test_winevt.rb

We should call `EvtCancel` on refreshing or cancelling subscription/query handles:
* https://docs.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtcancel

Cancel long living operations

---

ext/winevt/winevt_c.h
ext/winevt/winevt_query.c
ext/winevt/winevt_subscribe.c
ext/winevt/winevt_utils.cpp

There are some cases that Win32 API fails, but the error code is not get correctly (ErrorCode = 0)
This situation occurs because GetLastError is not called appropriately.

Do not override error code

---

ext/winevt/winevt_utils.cpp

`CHAR* ptr;` variable is not initailized by NULL.
For memory safety, we should use `ZeroMemory` to clear with '\0'.
Otherwise, ptr will have a garbage value.
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>
Maybe related to https://github.com/fluent/fluent-plugin-windows-eventlog/issues/79

utils: Use ZeroMemory for safety

---

ext/winevt/winevt.c
ext/winevt/winevt_c.h
ext/winevt/winevt_query.c
ext/winevt/winevt_subscribe.c
ext/winevt/winevt_utils.cpp
test/test_winevt.rb

Our customer who uses fluent-plugin-windows-evnetlog wants to skip unknown channels without stoping Fluentd. It's reasonable because channels are dynamically added or removed. But winevt_c doesn't provide a way to distinguish `ERROR_EVT_CHANNEL_NOT_FOUND` and other errors.
This commit adds `Winevt::EventLog::ChannelNotFoundError` and raise it when `ERROR_EVT_CHANNEL_NOT_FOUND` is occurred.
Signed-off-by: Takuro Ashie <ashie@clear-code.com>

Add a new error Winevt::EventLog::ChannelNotFoundError

---

.github/workflows/linux.yml
ext/winevt/winevt.c
ext/winevt/winevt_c.h
ext/winevt/winevt_subscribe.c

With event signal system, we're able to check the status of the event subscriptions.
This could be helpful for detecting failure of the subscribed handles.
---
This pull type of subscription,
we need to add the following actions:
1. Create an EventObject for handling signal events
2. Reset signal when ERROR_NO_MORE_ITEMS from EvtNext
This should ensure the windows eventlog collection correctly.
Also, we shouldn't specify the INFINITE waiting on WaitForSingleObject
because this function is inside of enumerator.
So, it causes infinite blocking for this case.

Raise an exception if an event signal notifies a failure state on EvtSubscribe

---

ext/winevt/winevt_query.c

This patch is debugging purpose. I had supposed that this feature was already implemented but it is actually absent. 
The fourth parameter is going to handle a flag for query instances which are based on EvtQuery API:
```ruby
@query = Winevt::EventLog::Query.new("/path/to/channel_stored.evtx", "*", @session,
Winevt::EventLog::Query::Flag::FilePath | Winevt::EventLog::Query::Flag::TolerateQueryErrors)
```

query: Implement to traverse feature for stored evtx files

---

appveyor.yml
ext/winevt/extconf.rb
ext/winevt/winevt_c.h
ext/winevt/winevt_query.c
ext/winevt/winevt_subscribe.c
ext/winevt/winevt_utils.cpp
ruby_install.ps1

This is needed to compete for the competitor of elastic beats.
ref: https://www.elastic.co/guide/en/beats/filebeat/current/processor-translate-sid.html

Expand SID with actual user name and domain

---

ext/winevt/winevt_utils.cpp

S-1-15-3- prefixed SIDs are used for indicating capabilities and not mapped for the actual users.
We need to skip SID translation to eliminate the needless trying to translate SIDs.
ref: https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-identifiers#capability-sids

Skip SID translation for capability SIDs

---

ext/winevt/winevt_channel.c

`free(pProperty)` is executed as error handling,
and then `free(pProperty)` is executed again as cleanup with same pointer address.
https://github.com/fluent-plugins-nursery/winevt_c/blob/dde5d46e3fc7439550deabae1208f321ae9065c4/ext/winevt/winevt_channel.c#L124-L157
With double free, it causes SEGV.
So, this PR will fix this problem

winevt_channel: fix double free to avoid SEGV

---

Rakefile

I removed following lines by mistake at https://github.com/fluent-plugins-nursery/winevt_c/pull/50
```
require 'bundler'
Bundler::GemHelper.install_tasks
```
These lines are required for `release` task in rake command.

Rakefile: restore release task

---

ext/winevt/winevt_utils.cpp

`strdup()` allocate the heap and copy into the heap area.
If we allocated heap area when preparing the source data, we must release the area after `strdup()` invoked, like
https://github.com/fluent-plugins-nursery/winevt_c/blob/576256d89b3180d19a1ddaf543f6e7cb59402a8d/ext/winevt/winevt_utils.cpp#L672-L676

winevt_utils: fix memory leak when handle SID
